import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Iniciando seed de la base de datos...')

  // Limpiar datos existentes (en orden correcto por las relaciones)
  console.log('🧹 Limpiando datos existentes...')
  await prisma.itemPedido.deleteMany()
  await prisma.factura.deleteMany()
  await prisma.albaran.deleteMany()
  await prisma.pedido.deleteMany()
  await prisma.producto.deleteMany()
  await prisma.user.deleteMany()

  // Crear usuario admin
  console.log('👤 Creando usuario admin...')
  const hashedPasswordAdmin = bcrypt.hashSync('admin123', 10)
  const admin = await prisma.user.create({
    data: {
      email: 'admin@spheratile.com',
      password: hashedPasswordAdmin,
      nombre: 'Administrador',
      role: 'ADMIN',
      telefono: '+34 964 123 456',
      empresa: 'SPHERA TILE S.L.',
      nif_cif: 'B12345678',
      direccion: 'Pol. Industrial Norte, Nave 15',
      ciudad: 'Onda',
      provincia: 'Castellón',
      codigo_postal: '12200',
    },
  })
  console.log(`   ✅ Admin creado: ${admin.email}`)

  // Crear clientes de prueba
  console.log('👥 Creando clientes de prueba...')
  const hashedPasswordCliente = bcrypt.hashSync('cliente123', 10)

  const clientes = await Promise.all([
    prisma.user.create({
      data: {
        email: 'construcciones.martinez@email.com',
        password: hashedPasswordCliente,
        nombre: 'Juan Martínez García',
        role: 'CLIENTE',
        telefono: '+34 666 111 222',
        empresa: 'Construcciones Martínez S.L.',
        nif_cif: 'B87654321',
        direccion: 'Calle Mayor 45, Local 2',
        ciudad: 'Valencia',
        provincia: 'Valencia',
        codigo_postal: '46001',
      },
    }),
    prisma.user.create({
      data: {
        email: 'reformas.lopez@email.com',
        password: hashedPasswordCliente,
        nombre: 'María López Sánchez',
        role: 'CLIENTE',
        telefono: '+34 666 333 444',
        empresa: 'Reformas López',
        nif_cif: 'B11223344',
        direccion: 'Av. del Puerto 123',
        ciudad: 'Castellón',
        provincia: 'Castellón',
        codigo_postal: '12003',
      },
    }),
    prisma.user.create({
      data: {
        email: 'ceramicas.garcia@email.com',
        password: hashedPasswordCliente,
        nombre: 'Antonio García Ruiz',
        role: 'CLIENTE',
        telefono: '+34 666 555 666',
        empresa: 'Cerámicas García e Hijos',
        nif_cif: 'B55667788',
        direccion: 'Polígono Industrial Sur, Parcela 8',
        ciudad: 'Almassora',
        provincia: 'Castellón',
        codigo_postal: '12550',
      },
    }),
    prisma.user.create({
      data: {
        email: 'decoracion.alba@email.com',
        password: hashedPasswordCliente,
        nombre: 'Alba Fernández Torres',
        role: 'CLIENTE',
        telefono: '+34 666 777 888',
        empresa: 'Decoración Alba',
        nif_cif: 'B99001122',
        direccion: 'Calle Colón 78, 3º',
        ciudad: 'Alicante',
        provincia: 'Alicante',
        codigo_postal: '03001',
      },
    }),
    prisma.user.create({
      data: {
        email: 'pedro.constructor@email.com',
        password: hashedPasswordCliente,
        nombre: 'Pedro Navarro Díaz',
        role: 'CLIENTE',
        telefono: '+34 666 999 000',
        empresa: null,
        nif_cif: '12345678A',
        direccion: 'Calle San Vicente 22',
        ciudad: 'Burriana',
        provincia: 'Castellón',
        codigo_postal: '12530',
      },
    }),
  ])
  console.log(`   ✅ ${clientes.length} clientes creados`)

  // Crear productos
  console.log('📦 Creando productos...')
  const productos = await Promise.all([
    // Serie MARMO
    prisma.producto.create({
      data: {
        slug: 'marmo-bianco-60x120',
        referencia: 'MRB-60120-01',
        nombre: 'Marmo Bianco',
        serie: 'MARMO',
        imagen: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=800',
        galeria: [],
        formato: '60x120',
        precio_m2: 32.50,
        stock_m2: 450,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'MARMOL',
        acabado: 'PULIDO',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO_REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Porcelánico efecto mármol blanco con vetas grises. Acabado pulido de alta calidad.',
        m2_caja: 1.44,
        piezas_caja: 2,
        m2_palet: 51.84,
        cajas_palet: 36,
        peso_caja_kg: 32,
        pedido_minimo_m2: 20,
      },
    }),
    prisma.producto.create({
      data: {
        slug: 'marmo-grigio-60x120',
        referencia: 'MRG-60120-01',
        nombre: 'Marmo Grigio',
        serie: 'MARMO',
        imagen: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800',
        galeria: [],
        formato: '60x120',
        precio_m2: 34.00,
        stock_m2: 320,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'MARMOL',
        acabado: 'PULIDO',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO_REVESTIMIENTO',
        estado_producto: 'NOVEDAD',
        descripcion: 'Porcelánico efecto mármol gris con veteado natural.',
        m2_caja: 1.44,
        piezas_caja: 2,
        m2_palet: 51.84,
        cajas_palet: 36,
        peso_caja_kg: 32,
        pedido_minimo_m2: 20,
      },
    }),
    prisma.producto.create({
      data: {
        slug: 'marmo-nero-60x120',
        referencia: 'MRN-60120-01',
        nombre: 'Marmo Nero',
        serie: 'MARMO',
        imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        galeria: [],
        formato: '60x120',
        precio_m2: 36.00,
        stock_m2: 180,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'MARMOL',
        acabado: 'PULIDO',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO_REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Porcelánico efecto mármol negro con vetas doradas.',
        m2_caja: 1.44,
        piezas_caja: 2,
        m2_palet: 51.84,
        cajas_palet: 36,
        peso_caja_kg: 32,
        pedido_minimo_m2: 20,
      },
    }),

    // Serie FOREST
    prisma.producto.create({
      data: {
        slug: 'forest-roble-20x120',
        referencia: 'FOR-20120-RB',
        nombre: 'Forest Roble',
        serie: 'FOREST',
        imagen: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800',
        galeria: [],
        formato: '20x120',
        precio_m2: 24.90,
        stock_m2: 680,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'MADERA',
        acabado: 'MATE',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Porcelánico imitación madera de roble natural. Ideal para interiores cálidos.',
        m2_caja: 0.96,
        piezas_caja: 4,
        m2_palet: 46.08,
        cajas_palet: 48,
        peso_caja_kg: 22,
        pedido_minimo_m2: 15,
      },
    }),
    prisma.producto.create({
      data: {
        slug: 'forest-nogal-20x120',
        referencia: 'FOR-20120-NG',
        nombre: 'Forest Nogal',
        serie: 'FOREST',
        imagen: 'https://images.unsplash.com/photo-1594940403429-a47b12a8a62b?w=800',
        galeria: [],
        formato: '20x120',
        precio_m2: 24.90,
        stock_m2: 520,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'MADERA',
        acabado: 'MATE',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Porcelánico imitación madera de nogal oscuro.',
        m2_caja: 0.96,
        piezas_caja: 4,
        m2_palet: 46.08,
        cajas_palet: 48,
        peso_caja_kg: 22,
        pedido_minimo_m2: 15,
      },
    }),
    prisma.producto.create({
      data: {
        slug: 'forest-fresno-20x120',
        referencia: 'FOR-20120-FR',
        nombre: 'Forest Fresno',
        serie: 'FOREST',
        imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        galeria: [],
        formato: '20x120',
        precio_m2: 22.50,
        stock_m2: 75,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'MADERA',
        acabado: 'MATE',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO',
        estado_producto: 'OFERTA',
        descripcion: 'Porcelánico imitación madera de fresno claro. ¡En oferta!',
        m2_caja: 0.96,
        piezas_caja: 4,
        m2_palet: 46.08,
        cajas_palet: 48,
        peso_caja_kg: 22,
        pedido_minimo_m2: 15,
      },
    }),

    // Serie CEMENT
    prisma.producto.create({
      data: {
        slug: 'cement-grey-60x60',
        referencia: 'CEM-6060-GR',
        nombre: 'Cement Grey',
        serie: 'CEMENT',
        imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        galeria: [],
        formato: '60x60',
        precio_m2: 18.90,
        stock_m2: 890,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'CEMENTO',
        acabado: 'MATE',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO_REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Porcelánico efecto cemento gris. Estilo industrial moderno.',
        m2_caja: 1.08,
        piezas_caja: 3,
        m2_palet: 43.20,
        cajas_palet: 40,
        peso_caja_kg: 24,
        pedido_minimo_m2: 20,
      },
    }),
    prisma.producto.create({
      data: {
        slug: 'cement-anthracite-60x60',
        referencia: 'CEM-6060-AN',
        nombre: 'Cement Anthracite',
        serie: 'CEMENT',
        imagen: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=800',
        galeria: [],
        formato: '60x60',
        precio_m2: 19.50,
        stock_m2: 650,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'CEMENTO',
        acabado: 'MATE',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO_REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Porcelánico efecto cemento antracita. Elegancia urbana.',
        m2_caja: 1.08,
        piezas_caja: 3,
        m2_palet: 43.20,
        cajas_palet: 40,
        peso_caja_kg: 24,
        pedido_minimo_m2: 20,
      },
    }),
    prisma.producto.create({
      data: {
        slug: 'cement-white-60x60',
        referencia: 'CEM-6060-WH',
        nombre: 'Cement White',
        serie: 'CEMENT',
        imagen: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800',
        galeria: [],
        formato: '60x60',
        precio_m2: 18.90,
        stock_m2: 420,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'CEMENTO',
        acabado: 'MATE',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO_REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Porcelánico efecto cemento blanco. Minimalismo puro.',
        m2_caja: 1.08,
        piezas_caja: 3,
        m2_palet: 43.20,
        cajas_palet: 40,
        peso_caja_kg: 24,
        pedido_minimo_m2: 20,
      },
    }),

    // Serie STONE
    prisma.producto.create({
      data: {
        slug: 'stone-beige-40x80',
        referencia: 'STN-4080-BG',
        nombre: 'Stone Beige',
        serie: 'STONE',
        imagen: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800',
        galeria: [],
        formato: '40x80',
        precio_m2: 26.00,
        stock_m2: 380,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'PIEDRA',
        acabado: 'TEXTURIZADO',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO_REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Porcelánico efecto piedra natural beige con textura antideslizante.',
        m2_caja: 1.28,
        piezas_caja: 4,
        m2_palet: 51.20,
        cajas_palet: 40,
        peso_caja_kg: 28,
        pedido_minimo_m2: 20,
      },
    }),
    prisma.producto.create({
      data: {
        slug: 'stone-grey-40x80',
        referencia: 'STN-4080-GR',
        nombre: 'Stone Grey',
        serie: 'STONE',
        imagen: 'https://images.unsplash.com/photo-1594940403429-a47b12a8a62b?w=800',
        galeria: [],
        formato: '40x80',
        precio_m2: 26.00,
        stock_m2: 290,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'PIEDRA',
        acabado: 'TEXTURIZADO',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO_REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Porcelánico efecto piedra natural gris con textura antideslizante.',
        m2_caja: 1.28,
        piezas_caja: 4,
        m2_palet: 51.20,
        cajas_palet: 40,
        peso_caja_kg: 28,
        pedido_minimo_m2: 20,
      },
    }),

    // Serie TERRA
    prisma.producto.create({
      data: {
        slug: 'terra-cotto-30x30',
        referencia: 'TER-3030-CT',
        nombre: 'Terra Cotto',
        serie: 'TERRA',
        imagen: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=800',
        galeria: [],
        formato: '30x30',
        precio_m2: 15.90,
        stock_m2: 560,
        calidad: 'PRIMERA',
        materia_prima: 'GRES',
        aspecto: 'TERRACOTA',
        acabado: 'MATE',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Gres rústico efecto terracota. Estilo mediterráneo tradicional.',
        m2_caja: 1.08,
        piezas_caja: 12,
        m2_palet: 43.20,
        cajas_palet: 40,
        peso_caja_kg: 20,
        pedido_minimo_m2: 15,
      },
    }),

    // Serie BASIC (Azulejos económicos)
    prisma.producto.create({
      data: {
        slug: 'basic-blanco-brillo-20x60',
        referencia: 'BAS-2060-BB',
        nombre: 'Basic Blanco Brillo',
        serie: 'BASIC',
        imagen: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800',
        galeria: [],
        formato: '20x60',
        precio_m2: 9.90,
        stock_m2: 1200,
        calidad: 'PRIMERA',
        materia_prima: 'AZULEJO',
        aspecto: 'BLANCO',
        acabado: 'PULIDO',
        tipo_pieza: 'BASE',
        uso: 'REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Azulejo blanco brillo básico. Ideal para baños y cocinas.',
        m2_caja: 1.20,
        piezas_caja: 10,
        m2_palet: 48.00,
        cajas_palet: 40,
        peso_caja_kg: 18,
        pedido_minimo_m2: 10,
      },
    }),
    prisma.producto.create({
      data: {
        slug: 'basic-blanco-mate-20x60',
        referencia: 'BAS-2060-BM',
        nombre: 'Basic Blanco Mate',
        serie: 'BASIC',
        imagen: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800',
        galeria: [],
        formato: '20x60',
        precio_m2: 9.50,
        stock_m2: 980,
        calidad: 'PRIMERA',
        materia_prima: 'AZULEJO',
        aspecto: 'BLANCO',
        acabado: 'MATE',
        tipo_pieza: 'BASE',
        uso: 'REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Azulejo blanco mate básico. Acabado suave y elegante.',
        m2_caja: 1.20,
        piezas_caja: 10,
        m2_palet: 48.00,
        cajas_palet: 40,
        peso_caja_kg: 18,
        pedido_minimo_m2: 10,
      },
    }),

    // Decorados
    prisma.producto.create({
      data: {
        slug: 'decor-geometrico-20x60',
        referencia: 'DEC-2060-GEO',
        nombre: 'Decor Geométrico',
        serie: 'DECOR',
        imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        galeria: [],
        formato: '20x60',
        precio_m2: 45.00,
        stock_m2: 85,
        calidad: 'PRIMERA',
        materia_prima: 'AZULEJO',
        aspecto: 'COLORES',
        acabado: 'SATINADO',
        tipo_pieza: 'DECORADO',
        uso: 'REVESTIMIENTO',
        estado_producto: 'NOVEDAD',
        descripcion: 'Azulejo decorativo con patrón geométrico moderno.',
        m2_caja: 1.20,
        piezas_caja: 10,
        m2_palet: 48.00,
        cajas_palet: 40,
        peso_caja_kg: 18,
        pedido_minimo_m2: 5,
      },
    }),
    prisma.producto.create({
      data: {
        slug: 'decor-floral-20x60',
        referencia: 'DEC-2060-FLO',
        nombre: 'Decor Floral',
        serie: 'DECOR',
        imagen: 'https://images.unsplash.com/photo-1594940403429-a47b12a8a62b?w=800',
        galeria: [],
        formato: '20x60',
        precio_m2: 42.00,
        stock_m2: 65,
        calidad: 'PRIMERA',
        materia_prima: 'AZULEJO',
        aspecto: 'COLORES',
        acabado: 'SATINADO',
        tipo_pieza: 'DECORADO',
        uso: 'REVESTIMIENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Azulejo decorativo con motivos florales elegantes.',
        m2_caja: 1.20,
        piezas_caja: 10,
        m2_palet: 48.00,
        cajas_palet: 40,
        peso_caja_kg: 18,
        pedido_minimo_m2: 5,
      },
    }),

    // Peldaños / Multistep
    prisma.producto.create({
      data: {
        slug: 'step-forest-roble-20x120',
        referencia: 'STP-20120-RB',
        nombre: 'Step Forest Roble',
        serie: 'FOREST',
        imagen: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800',
        galeria: [],
        formato: '20x120',
        precio_m2: 38.00,
        stock_m2: 120,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'MADERA',
        acabado: 'TEXTURIZADO',
        tipo_pieza: 'MULTISTEP',
        uso: 'PAVIMENTO',
        estado_producto: 'NORMAL',
        descripcion: 'Peldaño porcelánico imitación roble con nariz antideslizante.',
        m2_caja: 0.48,
        piezas_caja: 2,
        m2_palet: 23.04,
        cajas_palet: 48,
        peso_caja_kg: 15,
        pedido_minimo_m2: 10,
      },
    }),

    // Producto con bajo stock para probar alertas
    prisma.producto.create({
      data: {
        slug: 'marmo-calacatta-60x120',
        referencia: 'MRC-60120-01',
        nombre: 'Marmo Calacatta',
        serie: 'MARMO',
        imagen: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=800',
        galeria: [],
        formato: '60x120',
        precio_m2: 48.00,
        stock_m2: 45,
        calidad: 'PRIMERA',
        materia_prima: 'PORCELANICO',
        aspecto: 'MARMOL',
        acabado: 'PULIDO',
        tipo_pieza: 'BASE',
        uso: 'PAVIMENTO_REVESTIMIENTO',
        estado_producto: 'OFERTA',
        descripcion: 'Porcelánico efecto mármol Calacatta premium. ¡Últimas unidades en oferta!',
        m2_caja: 1.44,
        piezas_caja: 2,
        m2_palet: 51.84,
        cajas_palet: 36,
        peso_caja_kg: 32,
        pedido_minimo_m2: 20,
      },
    }),
  ])
  console.log(`   ✅ ${productos.length} productos creados`)

  // Crear un pedido de ejemplo
  console.log('📋 Creando pedido de ejemplo...')
  const pedido = await prisma.pedido.create({
    data: {
      numero_pedido: `PED-${new Date().getFullYear()}-00001`,
      userId: clientes[0].id,
      direccion_envio: 'Calle Mayor 45, Local 2',
      ciudad: 'Valencia',
      provincia: 'Valencia',
      codigo_postal: '46001',
      notas: 'Entregar por la mañana antes de las 12:00',
      total_m2: 50.40,
      subtotal_euros: 1260.00,
      iva_porcentaje: 21,
      iva_euros: 264.60,
      total_euros: 1524.60,
      estado: 'CONFIRMADO',
      items: {
        create: [
          {
            productoId: productos[0].id,
            producto_nombre: productos[0].nombre,
            producto_referencia: productos[0].referencia,
            cantidad_m2: 28.80,
            cantidad_cajas: 20,
            precio_m2: 32.50,
            subtotal: 936.00,
          },
          {
            productoId: productos[7].id,
            producto_nombre: productos[7].nombre,
            producto_referencia: productos[7].referencia,
            cantidad_m2: 21.60,
            cantidad_cajas: 20,
            precio_m2: 15.00,
            subtotal: 324.00,
          },
        ],
      },
    },
  })
  console.log(`   ✅ Pedido ${pedido.numero_pedido} creado`)

  console.log('')
  console.log('🎉 Seed completado exitosamente!')
  console.log('')
  console.log('📝 Credenciales de acceso:')
  console.log('   Admin: admin@spheratile.com / admin123')
  console.log('   Cliente: construcciones.martinez@email.com / cliente123')
  console.log('')
}

main()
  .catch((e) => {
    console.error('❌ Error en el seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
