import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import bcrypt from 'bcryptjs'

// Imágenes de Unsplash para productos
const IMG = {
  marmol1: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=800&q=80',
  marmol2: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80',
  marmol3: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
  cemento1: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&q=80',
  cemento2: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
  madera1: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
  madera2: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80',
  piedra1: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
  piedra2: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&q=80',
  blanco1: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80',
  colores1: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=800&q=80',
  terracota1: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80',
  ambiente1: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
  ambiente2: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
}

const productosData = [
  // Porcelánico Mármol
  {
    slug: 'calacatta-gold-pulido',
    referencia: 'CAL-GOLD-120',
    nombre: 'Calacatta Gold Pulido',
    serie: 'Luxury Marble',
    imagen: IMG.marmol1,
    galeria: [IMG.ambiente1, IMG.marmol2],
    formato: '120x120 cm',
    precio_m2: 89.90,
    stock_m2: 450,
    calidad: 'PRIMERA',
    materia_prima: 'PORCELANICO',
    aspecto: 'MARMOL',
    acabado: 'PULIDO',
    tipo_pieza: 'BASE',
    uso: 'PAVIMENTO_REVESTIMIENTO',
    estado_producto: 'NOVEDAD',
    descripcion: 'Porcelánico de alta gama con vetas doradas sobre fondo blanco',
    m2_caja: 1.44,
    piezas_caja: 1,
    m2_palet: 43.2,
    cajas_palet: 30,
    peso_caja_kg: 32,
    pedido_minimo_m2: 14.4,
  },
  {
    slug: 'statuario-mate',
    referencia: 'STA-MAT-80',
    nombre: 'Statuario Mate',
    serie: 'Luxury Marble',
    imagen: IMG.marmol2,
    galeria: [IMG.marmol3],
    formato: '80x80 cm',
    precio_m2: 72.50,
    stock_m2: 320,
    calidad: 'PRIMERA',
    materia_prima: 'PORCELANICO',
    aspecto: 'MARMOL',
    acabado: 'MATE',
    tipo_pieza: 'BASE',
    uso: 'PAVIMENTO_REVESTIMIENTO',
    estado_producto: 'NORMAL',
    descripcion: 'Elegante mármol con acabado mate',
    m2_caja: 1.28,
    piezas_caja: 2,
    m2_palet: 38.4,
    cajas_palet: 30,
    peso_caja_kg: 28,
    pedido_minimo_m2: 12.8,
  },
  // Porcelánico Cemento
  {
    slug: 'urban-grey-mate',
    referencia: 'URB-GRY-60',
    nombre: 'Urban Grey Mate',
    serie: 'Urban Collection',
    imagen: IMG.cemento1,
    galeria: [IMG.cemento2],
    formato: '60x60 cm',
    precio_m2: 32.90,
    stock_m2: 850,
    calidad: 'PRIMERA',
    materia_prima: 'PORCELANICO',
    aspecto: 'CEMENTO',
    acabado: 'MATE',
    tipo_pieza: 'BASE',
    uso: 'PAVIMENTO',
    estado_producto: 'NORMAL',
    descripcion: 'Efecto cemento urbano moderno',
    m2_caja: 1.44,
    piezas_caja: 4,
    m2_palet: 43.2,
    cajas_palet: 30,
    peso_caja_kg: 25,
    pedido_minimo_m2: 14.4,
  },
  {
    slug: 'concrete-dark-antislip',
    referencia: 'CON-DRK-60',
    nombre: 'Concrete Dark Antislip',
    serie: 'Urban Collection',
    imagen: IMG.cemento2,
    galeria: [IMG.cemento1],
    formato: '60x60 cm',
    precio_m2: 38.50,
    stock_m2: 520,
    calidad: 'PRIMERA',
    materia_prima: 'PORCELANICO',
    aspecto: 'CEMENTO',
    acabado: 'TEXTURIZADO',
    tipo_pieza: 'BASE',
    uso: 'PAVIMENTO',
    estado_producto: 'OFERTA',
    descripcion: 'Cemento oscuro con acabado antideslizante',
    m2_caja: 1.44,
    piezas_caja: 4,
    m2_palet: 43.2,
    cajas_palet: 30,
    peso_caja_kg: 26,
    pedido_minimo_m2: 14.4,
  },
  // Porcelánico Madera
  {
    slug: 'roble-natural-mate',
    referencia: 'ROB-NAT-20',
    nombre: 'Roble Natural Mate',
    serie: 'Wood Essence',
    imagen: IMG.madera1,
    galeria: [IMG.madera2],
    formato: '20x120 cm',
    precio_m2: 28.90,
    stock_m2: 1200,
    calidad: 'PRIMERA',
    materia_prima: 'PORCELANICO',
    aspecto: 'MADERA',
    acabado: 'MATE',
    tipo_pieza: 'BASE',
    uso: 'PAVIMENTO',
    estado_producto: 'NORMAL',
    descripcion: 'Imitación roble con vetas naturales',
    m2_caja: 0.96,
    piezas_caja: 4,
    m2_palet: 28.8,
    cajas_palet: 30,
    peso_caja_kg: 22,
    pedido_minimo_m2: 9.6,
  },
  {
    slug: 'nogal-oscuro-satinado',
    referencia: 'NOG-OSC-20',
    nombre: 'Nogal Oscuro Satinado',
    serie: 'Wood Essence',
    imagen: IMG.madera2,
    galeria: [IMG.madera1],
    formato: '20x120 cm',
    precio_m2: 34.50,
    stock_m2: 680,
    calidad: 'PRIMERA',
    materia_prima: 'PORCELANICO',
    aspecto: 'MADERA',
    acabado: 'SATINADO',
    tipo_pieza: 'BASE',
    uso: 'PAVIMENTO',
    estado_producto: 'NOVEDAD',
    descripcion: 'Elegante nogal con acabado satinado',
    m2_caja: 0.96,
    piezas_caja: 4,
    m2_palet: 28.8,
    cajas_palet: 30,
    peso_caja_kg: 22,
    pedido_minimo_m2: 9.6,
  },
  // Porcelánico Piedra
  {
    slug: 'slate-grey-texturizado',
    referencia: 'SLA-GRY-60',
    nombre: 'Slate Grey Texturizado',
    serie: 'Stone Collection',
    imagen: IMG.piedra1,
    galeria: [IMG.piedra2],
    formato: '60x60 cm',
    precio_m2: 42.00,
    stock_m2: 380,
    calidad: 'PRIMERA',
    materia_prima: 'PORCELANICO',
    aspecto: 'PIEDRA',
    acabado: 'TEXTURIZADO',
    tipo_pieza: 'BASE',
    uso: 'PAVIMENTO_REVESTIMIENTO',
    estado_producto: 'NORMAL',
    descripcion: 'Pizarra gris con textura natural',
    m2_caja: 1.44,
    piezas_caja: 4,
    m2_palet: 43.2,
    cajas_palet: 30,
    peso_caja_kg: 27,
    pedido_minimo_m2: 14.4,
  },
  // Gres
  {
    slug: 'terracota-rustic',
    referencia: 'TER-RUS-40',
    nombre: 'Terracota Rustic',
    serie: 'Mediterranean',
    imagen: IMG.terracota1,
    galeria: [],
    formato: '40x40 cm',
    precio_m2: 22.50,
    stock_m2: 950,
    calidad: 'PRIMERA',
    materia_prima: 'GRES',
    aspecto: 'TERRACOTA',
    acabado: 'MATE',
    tipo_pieza: 'BASE',
    uso: 'PAVIMENTO',
    estado_producto: 'NORMAL',
    descripcion: 'Terracota rústica mediterránea',
    m2_caja: 1.28,
    piezas_caja: 8,
    m2_palet: 38.4,
    cajas_palet: 30,
    peso_caja_kg: 24,
    pedido_minimo_m2: 12.8,
  },
  {
    slug: 'economic-grey',
    referencia: 'ECO-GRY-40',
    nombre: 'Economic Grey',
    serie: 'Basic Line',
    imagen: IMG.cemento1,
    galeria: [],
    formato: '40x40 cm',
    precio_m2: 12.50,
    stock_m2: 2500,
    calidad: 'COM',
    materia_prima: 'GRES',
    aspecto: 'CEMENTO',
    acabado: 'MATE',
    tipo_pieza: 'BASE',
    uso: 'PAVIMENTO',
    estado_producto: 'OFERTA',
    descripcion: 'Gres económico para grandes superficies',
    m2_caja: 1.28,
    piezas_caja: 8,
    m2_palet: 38.4,
    cajas_palet: 30,
    peso_caja_kg: 23,
    pedido_minimo_m2: 25.6,
  },
  // Azulejo
  {
    slug: 'blanco-brillo-rectificado',
    referencia: 'BLA-BRI-30',
    nombre: 'Blanco Brillo Rectificado',
    serie: 'Pure White',
    imagen: IMG.blanco1,
    galeria: [],
    formato: '30x60 cm',
    precio_m2: 18.90,
    stock_m2: 1800,
    calidad: 'PRIMERA',
    materia_prima: 'AZULEJO',
    aspecto: 'BLANCO',
    acabado: 'PULIDO',
    tipo_pieza: 'BASE',
    uso: 'REVESTIMIENTO',
    estado_producto: 'NORMAL',
    descripcion: 'Azulejo blanco brillante rectificado',
    m2_caja: 1.08,
    piezas_caja: 6,
    m2_palet: 32.4,
    cajas_palet: 30,
    peso_caja_kg: 18,
    pedido_minimo_m2: 10.8,
  },
  {
    slug: 'zellige-emerald',
    referencia: 'ZEL-EME-10',
    nombre: 'Zellige Emerald',
    serie: 'Artisan Collection',
    imagen: IMG.colores1,
    galeria: [],
    formato: '10x10 cm',
    precio_m2: 48.00,
    stock_m2: 280,
    calidad: 'PRIMERA',
    materia_prima: 'AZULEJO',
    aspecto: 'COLORES',
    acabado: 'SATINADO',
    tipo_pieza: 'DECORADO',
    uso: 'REVESTIMIENTO',
    estado_producto: 'NOVEDAD',
    descripcion: 'Zellige artesanal color esmeralda',
    m2_caja: 0.88,
    piezas_caja: 88,
    m2_palet: 26.4,
    cajas_palet: 30,
    peso_caja_kg: 14,
    pedido_minimo_m2: 8.8,
  },
  {
    slug: 'subway-white-mate',
    referencia: 'SUB-WHT-10',
    nombre: 'Subway White Mate',
    serie: 'Metro Collection',
    imagen: IMG.blanco1,
    galeria: [],
    formato: '10x20 cm',
    precio_m2: 15.90,
    stock_m2: 2200,
    calidad: 'PRIMERA',
    materia_prima: 'AZULEJO',
    aspecto: 'BLANCO',
    acabado: 'MATE',
    tipo_pieza: 'BASE',
    uso: 'REVESTIMIENTO',
    estado_producto: 'NORMAL',
    descripcion: 'Clásico metro blanco mate',
    m2_caja: 1.0,
    piezas_caja: 50,
    m2_palet: 30.0,
    cajas_palet: 30,
    peso_caja_kg: 16,
    pedido_minimo_m2: 10.0,
  },
  // Decorados y Multistep
  {
    slug: 'cenefa-marmol-gold',
    referencia: 'CEN-MAR-10',
    nombre: 'Cenefa Mármol Gold',
    serie: 'Luxury Marble',
    imagen: IMG.marmol1,
    galeria: [],
    formato: '10x60 cm',
    precio_m2: 125.00,
    stock_m2: 85,
    calidad: 'PRIMERA',
    materia_prima: 'PORCELANICO',
    aspecto: 'MARMOL',
    acabado: 'PULIDO',
    tipo_pieza: 'DECORADO',
    uso: 'REVESTIMIENTO',
    estado_producto: 'NORMAL',
    descripcion: 'Cenefa decorativa con detalles dorados',
    m2_caja: 0.36,
    piezas_caja: 6,
    m2_palet: 10.8,
    cajas_palet: 30,
    peso_caja_kg: 8,
    pedido_minimo_m2: 3.6,
  },
  {
    slug: 'peldano-urban-grey',
    referencia: 'PEL-URB-33',
    nombre: 'Peldaño Urban Grey',
    serie: 'Urban Collection',
    imagen: IMG.cemento1,
    galeria: [],
    formato: '33x60 cm',
    precio_m2: 45.00,
    stock_m2: 150,
    calidad: 'PRIMERA',
    materia_prima: 'PORCELANICO',
    aspecto: 'CEMENTO',
    acabado: 'TEXTURIZADO',
    tipo_pieza: 'MULTISTEP',
    uso: 'PAVIMENTO',
    estado_producto: 'NORMAL',
    descripcion: 'Peldaño con nariz antideslizante',
    m2_caja: 0.99,
    piezas_caja: 5,
    m2_palet: 29.7,
    cajas_palet: 30,
    peso_caja_kg: 22,
    pedido_minimo_m2: 9.9,
  },
]

export async function POST() {
  try {
    // Verificar si ya existe el admin
    const existingAdmin = await prisma.user.findUnique({
      where: { email: 'admin@spheratile.com' },
    })

    if (!existingAdmin) {
      // Crear usuario admin
      const hashedPassword = bcrypt.hashSync('admin123', 10)
      await prisma.user.create({
        data: {
          email: 'admin@spheratile.com',
          password: hashedPassword,
          nombre: 'Administrador',
          role: 'ADMIN',
        },
      })
    }

    // Verificar si ya hay productos
    const productCount = await prisma.producto.count()

    if (productCount === 0) {
      // Crear productos
      for (const producto of productosData) {
        await prisma.producto.create({
          data: producto as any,
        })
      }
    }

    const finalProductCount = await prisma.producto.count()
    const userCount = await prisma.user.count()

    return NextResponse.json({
      success: true,
      message: 'Seed completado',
      data: {
        usuarios: userCount,
        productos: finalProductCount,
        adminEmail: 'admin@spheratile.com',
        adminPassword: 'admin123',
      },
    })
  } catch (error) {
    console.error('Error en seed:', error)
    return NextResponse.json({ error: 'Error al ejecutar seed', details: String(error) }, { status: 500 })
  }
}
